version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    groups:
      deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'build: bump deps.'
    versioning-strategy: 'increase'
    allow:
      - dependency-type: 'all'

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'build(actions)'
