version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - 'src'
      - 'docs'
    schedule:
      interval: 'cron'
      cronjob: '0 9 * * *'
      timezone: 'Asia/Shanghai'
    groups:
      deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'build'
      include: scope
    versioning-strategy: 'auto'
    allow:
      - dependency-type: 'direct'

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: 'cron'
      cronjob: '0 9 * * *'
      timezone: 'Asia/Shanghai'
    commit-message:
      prefix: 'build'
      include: scope
