version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/docs'
      - '/src'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'build(deps)'

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'build(actions)'
